### PR TITLE
Add `.wast` output to Grain Playground

### PR DESCRIPTION
**Pull request by tomayac**
This PR makes the following improvements:

- Adds `.wast` output to the playground.
- Improves mobile and desktop layout.

Screenshots:

- Desktop:
   Screenshot 2024-01-29 at 15 55 37
- Mobile:
   Screenshot 2024-01-29 at 15 57 36

### CODE REVIEW

**Comment by phated** [comment]
This is awesome! I think we might want to hide it behind a toggle though since Grain's audience (especially playground users) isn't going to care about the wat output

**Comment by tomayac** [comment]
Thanks for the feedback. Added a checkbox that if and only if checked imports Binaryen and displays the `.wast` panel.

Screenshot 2024-01-31 at 12 43 37
Screenshot 2024-01-31 at 12 44 41
Screenshot 2024-01-31 at 12 43 58

**Comment by phated** [comment]
Hey @tomayac, sorry for the delay here. We appreciate you sending this change.

We discussed it during our community meeting and we think this will lead to more questions for Grain users than answers. The wat output is always available from the CLI but the playground is more about getting your feet wet.

Thanks again for sending this and we welcome other improvements you want to PR!

**Comment by tomayac** [comment]
Thanks, that's fair enough. I wanted this feature for an article, but can go with the [AssemblyScript playground](https://www.assemblyscript.org/) instead (whose `.wat` is less verbose, too, so it actually works better in the context of an article).

**Comment by tomayac** [comment]
Actually, you may want to profit from the CSS changes in this PR. It improves the rendering a lot. If you want, I'm happy to repurpose this PR to just improving the layout. Let me know…

**Comment by phated** [comment]
We'd love to pull in the CSS changes! ❤️

**Comment by tomayac** [comment]
@phated Please see #360.

**Pull request closed without merging**
