### PR TITLE
Document float32 and float64 libraries

### PR DESCRIPTION
**Pull request by ospencer**

### CODE REVIEW

**Review by phated — APPROVED** [review]
👍 What do you think about moving all the number libraries to the bottom of the list because they are less used than the other items?

**Comment by ospencer** [comment]
Do you think they should go above or below the `Sys` modules?

**Comment by phated** [comment]
@ospencer I'd move them below for now, it sort of gives a visual impression that they aren't needed unless you are doing type-specific math.

**Comment by ospencer** [comment]
I'll merge this and then PR a change to move them.

**Pull request merged**
