### PR TITLE
fix: Only highlight code blocks marked language grain

### PR DESCRIPTION
**Pull request by ospencer**
~~Draft for those sweet sweet website previews.~~

It appears to work!

### CODE REVIEW

**Comment by phated** [comment]
@ospencer looks like 1 example on the Pattern Matching page isn't marked as a `grain` codeblock

**Comment by ospencer** [comment]
Fixed that one!

**Review by phated — APPROVED** [review]
That seemed to be the only one that I could find. However, our syntax highlighting of `type Number` is weird (both `type` and `Number` are white).

**Comment by ospencer** [comment]
Ah yeah that looks broken on the live site. Largely because it's not supported Grain syntax haha. Made https://github.com/grain-lang/grain-language-server/issues/90 to address!

**Pull request merged**
